### ISSUE TITLE
Host Documentation on ReadTheDocs

### ISSUE THREAD

**Issue by johnthagen** [JoelLefkowitz/drf-yasg#9]
There are currently a lot of links pointing to https://drf-yasg2.readthedocs.io/ but these links don't work yet since the docs haven't been hosted yet.

**Comment by JoelLefkowitz** [comment]
Fixed

**Comment by johnthagen** [comment]
@JoelLefkowitz I still see "This page does not exist" at https://drf-yasg2.readthedocs.io/en/latest/. Should I be seeing the docs?

**Comment by marcosox** [comment]
I see the same 404. Doesn't seem to be fixed.

**Comment by johnthagen** [comment]
Also @JoelLefkowitz A few places (like in the README) and in the GitHub project info you have https://drf_yasg2.readthedocs.io/ instead of https://drf-yasg2.readthedocs.io/. It seems like it would be best to use the package name `drf-yasg2` everywhere (even doc URLs) for consistency. What do you think?

**Comment by johnthagen** [comment]
@JoelLefkowitz Could we reopen this issue? The docs are still not hosted. I think this and #24 are the last few issues needed before we are ready to say that `drf-yasg2` is fully ready for prime time.

**Comment by JoelLefkowitz** [comment]
The link is fine, it was the docs build that was failing. #63 Fixes this now.
